# Generated by Django 2.0.1 on 2018-01-22 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quote',
            name='sitestatus',
            field=models.CharField(choices=[('NEW', 'New Site'), ('EX', 'Existing Site')], max_length=20),
        ),
    ]
